name: ddp_graphcast
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - conda-forge::regionmask
  - conda-forge::xarray
  # DATASETS
  - conda-forge::xmip
  - conda-forge::cf_xarray
  - conda-forge::intake-esm
  # STUFF
  # VISUALIZATION
  - cartopy
  - cmocean
  - seaborn
  - matplotlib
  - xmovie
  - ipykernel
  - ffmpeg
  - pip
  - pip:
      - cookiecutter
      - autoroot
      - python-dateutil
      - pydantic
      # DATA ACCESS
      - climetlab
      - xee
      - ecmwf-api-client
      - cdsapi
      - gcsfs
      # OTHER
      # AI MODELS
      - git+https://github.com/NVIDIA/earth2mip.git
      # PANGU Dependencies
      - onnxruntime-gpu
      - "ruamel.yaml<0.18.0"
      # GRAPHCAST Dependencies
      - "flax==0.7.3"
      - "jax==0.4.16"
      - "graphcast @ https://github.com/deepmind/graphcast/archive/e622a15c1b9742d78f9b662f2af262604d58c204.tar.gz"
      # Extra Stuff
      - loguru 
      - tqdm
